

env: local


database:
  - host: localhost
    port: 5432
    name: test-psql-db
    password: SuperSecretPassword
    user: ADMIN_USER
    ssl: disable


server:
  - port: :8080

client:
  - api_url: http://localhost:3000
